-- The director for A Bug's Life is incorrect, it was actually directed by John Lasseter
-- The year that Toy Story 2 was released is incorrect, it was actually released in 1999
-- Both the title and director for Toy Story 8 is incorrect! The title should be "Toy Story 3" and it was directed by Lee Unkrich